import bcrypt from 'bcryptjs';
const data = {
  users: [
    // {
    //   name: 'Rick Tran',
    //   email: 'thangricktran@yahoo.com',
    //   password: bcrypt.hashSync('VerySecret'),
    //   isAdmin: true,
    // },
    // {
    //   name: 'Thang Tran',
    //   email: 'thangricktran2@gmail.com',
    //   password: bcrypt.hashSync('VerySecret'),
    //   isAdmin: true,
    // },
    // {
    //   name: 'Mary',
    //   email: 'mary@example.com',
    //   password: bcrypt.hashSync('verysecret'),
    //   isAdmin: false,
    // },
    {
      name: 'John Doe',
      email: 'john@doe.com',
      password: bcrypt.hashSync('verysecret'),
      isAdmin: false,
    },
    {
      name: 'Jane Jane',
      email: 'jane@jane.com',
      password: bcrypt.hashSync('verysecret'),
      isAdmin: false,
    },
    {
      name: 'Jane Doe',
      email: 'jane@doe.com',
      password: bcrypt.hashSync('verysecret'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      // countInStock: 20,
      description: 'A popular shirt',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
        {name: 'XS', price: 60, countInStock: 13},
        {name: 'S', price: 70, countInStock: 20},
        {name: 'M', price: 75, countInStock: 20},
        {name: 'L', price: 80, countInStock: 18},
        {name: 'XL', price: 85, countInStock: 5},
        {name: 'XXL', price: 85, countInStock: 3}
      ],
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      // countInStock: 20,
      description: 'A popular shirt',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
          {name: 'XS', price: 60, countInStock: 13,},
          {name: 'S', price: 70, countInStock: 20,},
          {name: 'M', price: 75, countInStock: 20,},
          {name: 'L', price: 80, countInStock: 18,},
          {name: 'XL', price: 85, countInStock: 5},
          {name: 'XXL', price: 85, countInStock: 5}
      ],
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      // countInStock: 20,
      description: 'A popular shirt',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
        {name: 'XS', price: 60, countInStock: 13,},
        {name: 'S', price: 80, countInStock: 20,},
        {name: 'M', price: 90, countInStock: 20,},
        {name: 'L', price: 85, countInStock: 18,},
        {name: 'XL', price: 55, countInStock: 5},
        {name: 'XXL', price: 55, countInStock: 4}
      ],
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      // countInStock: 20,
      description: 'Smart looking pants',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
        {name: 'XS', price: 60, countInStock: 13,},
        {name: 'S', price: 90, countInStock: 20,},
        {name: 'M', price: 95, countInStock: 20,},
        {name: 'L', price: 90, countInStock: 18,},
        {name: 'XL', price: 65, countInStock: 5},
        {name: 'XXL', price: 65, countInStock: 3}
      ],
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      // countInStock: 20,
      description: 'A popular pants',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
        {name: 'XS', price: 60, countInStock: 13,},
        {name: 'S', price: 80, countInStock: 20,},
        {name: 'M', price: 95, countInStock: 20,},
        {name: 'L', price: 90, countInStock: 18,},
        {name: 'XL', price: 80, countInStock: 5,},
        {name: 'XXL', price: 80, countInStock: 4}
      ],
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      // countInStock: 20,
      description: 'A popular pants',
      sizes: [
        {name: 'Select', price: 0, countInStock: 0,},
        {name: 'XS', price: 60, countInStock: 13,},
        {name: 'S', price: 70, countInStock: 20,},
        {name: 'M', price: 75, countInStock: 20,},
        {name: 'L', price: 70, countInStock: 18,},
        {name: 'XL', price: 65, countInStock: 5,},
        {name: 'XXL', price: 65, countInStock: 4}
      ],
    },
  ],
};

export default data;
